### ISSUE TITLE
Error with extractClusters (see below)

### ISSUE THREAD

**Issue by MboiTui** [petrikemppainen/LDna#18]
Hello Petri,

I am currently using LDna on a dataset of ~8000 SNPs. It works fine for some of my input data, but for one of my datasets I get an error at the `extractClusters` step (see below). The only way this dataset differs from the ones that work is that it has one less population. Processing, calculations of LD, etc are all done in the same way. 

Before I start digging into the code of `extractCluster` function I was wondering if you have encountered something similar before and maybe know what might be causing it?

```
Error in prop.part(tree)[[anc - n]] : attempt to select less than one element in get1index

5. | FUN(X[[i]], ...)

4. | lapply(SOCs, function(cl) { anc <- cl anc <- tree$edge[tree$edge[, 2] == which(tree$tip.label == anc), 1] ...

3. | do.call(rbind, lapply(SOCs, function(cl) { anc <- cl anc <- tree$edge[tree$edge[, 2] == which(tree$tip.label == anc), 1] ...

2. | branch_traversal(ldna, clusters = out, Summary = as.data.table(summaryLDna(ldna = ldna, clusters = out, LDmat = LDmat)), min.edges = min.edges, lambda.lim = lambda.lim, plot.tree = plot.tree)

1. | extractClusters(my.ldna[[2]], my.list.ld[[2]], extract = TRUE, plot.tree = FALSE)

```

**Comment by petrikemppainen** [comment]
Quick answer, with one population you have no clustering, so the function
does not work. Look at the histogram of LD, if you have very few high
values, ldna is not useful anymore, or try with different thresholds for
extracting clusters. This is on my to do list. Which version are you using?
Try the latest one...

**Comment by MboiTui** [comment]
Hello Petri,

Thank you for your quick answer. And apologies I was unclear in my original question.

When I said "one less population", I still have multiple populations (3 lineages, 400+ individuals). From contact zones and away from contact zones.

Quickly looking at histogram of LD, there are many values on the right tail. Enough to find clusters.

When I run extractCluster with plotTree=TRUE and extractCluster=FALSE it finds 3 SOCs (see tree attached). But when I run extractCluster with extractCluster=TRUE that's when the error arises.

**Histogram of R2 values**
![Screen Shot 2022-10-24 at 10 40 53 am](https://user-images.githubusercontent.com/26472198/197427096-00467d6c-0755-4766-b5fd-19100087457f.png)

**plot of lambda vs index**
![Screen Shot 2022-10-24 at 10 44 28 am](https://user-images.githubusercontent.com/26472198/197427115-24c8e74c-4d87-4453-bc3a-c024dd5913dd.png)

**Output of extractClusters with plotTree=True and extractCluster=FALSE**
![SOC_Trees](https://user-images.githubusercontent.com/26472198/197427160-03541819-3ade-470c-a644-d39b4e02dd53.png)

**Comment by petrikemppainen** [comment]
Actually, your threshold is already low, so basically only
populationstructuring in the data....

**Comment by MboiTui** [comment]
That's what I thought Petri upon looking at it in more detail. Thank you for your replies.

And apologies if this turned out to be a data issue and not an issue with the underlying package or code.

**Comment by petrikemppainen** [comment]
No worries and thank you for using LDna! It seems it was helpful in the way
it is intended to be, unfortunately it seems there was nothing hidden
lurking in the data that could have been interesting...
